name: flutter_forge
description: "Craft your app skills"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.3
  cupertino_icons: ^1.0.8
  dio: ^5.2.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.4
  get_it: ^7.6.0
  json_annotation: ^4.9.0
  i69n: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bdd_widget_test: ^1.7.6
  build_runner: ^2.4.14
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  mocktail: ^1.0.4
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
